### ISSUE TITLE
could be that docker compose have to be installed on the side?

### ISSUE THREAD

**Issue by santiagomoneta** [fmdlc/ISP-Checker#14]
I got some issues installing docker on my raspi4 for this project and hit a wall with a 'docker-compose command not found' and eventually solve this by running `sudo pip3 -v install docker-compose `.. is is expected?

**Comment by fmdlc** [comment]
@santiagomoneta Hi Santi, yes it's expected. Probably I can drop a note on the README.md. Thanks 💪
