### ISSUE TITLE
The speedtest might create a weird pattern in graphs.

### ISSUE THREAD

**Issue by edux** [fmdlc/ISP-Checker#2]
Having the speedtest run every 5 minutes create this pattern on the icmp graph. The speedtest-cli command running every 5 minutes saturates the uplink and generates the delay on the icmp response.

https://github.com/fmdlc/ISP-Checker/blob/45d6e299b7e23d3202b1bfa9266055cf1f8fe75d/ISP-Checker/telegraf/conf/telegraf.conf#L103

<img width="1580" alt="Screen Shot 2020-10-09 at 08 49 37" src="https://user-images.githubusercontent.com/857187/95595758-e90c5f00-0a22-11eb-8727-4b3769d6dd1c.png">

I don't know if it makes sense to change it or just leave it there for each user to decide.

**Comment by fdelacruz-asapp** [comment]
Probably we can limit the upload/download size and avoid this saturation. I will research, thanks for reporting @edux !

**Comment by fmdlc** [comment]
Probably we can limit the upload/download size and avoid this saturation. I will research, thanks for reporting @edux !

**Comment by edux** [comment]
I've been thinking how to tackle this, basically during work day I am ok if I get ~75% of my purchased bandwidth, so with some scripting we could do:

1st run: 
speedtest without limits, report back to telegraph and also save output to a local file.
next run and localfile timestamp <24hs then:
run speedtest but wrap it with tc shaping to a 75% of the bandwidth for up and down to not kill the uplink.
next run and localfile >24hs then:
run speedtest without limits and save the new bandwidth limit.

but probably this is over engineered.

**Comment by fmdlc** [comment]
@edux In order to fix this issue, I was focusing mostly on running on a Kubernetes cluster, for that I configured `speedtest-cli` and `mtr` to run like a `cronJob` every 10 minutes. Probably it had reduced the overhead produced while these two binaries were running. Let me close this Issue and don't hesitate to reach me out if some other issue happens.
