### ISSUE TITLE
The Bandwidth is in megabyte or megabit?

### ISSUE THREAD

**Issue by lcsvcn** [fmdlc/ISP-Checker#33]
I am a little confuse, the bandwidth is measured in megabyte or megabit per second?

My values are too low for Megabit, but I don't know if is unit or if is my ISP problem. I use any other speed test and it is app 
is pointing the right Mbps speed.

This is my grafana, I have changed to Mbps and this is my last hour results, I had an issue 2 hours before and take a while to normalize, but I think the data is in Mbps. 
![Screenshot from 2021-02-04 21-39-42](https://user-images.githubusercontent.com/6011385/106973377-878aa180-6731-11eb-9942-44ee48b60688.png)

![Screenshot from 2021-02-04 21-32-03](https://user-images.githubusercontent.com/6011385/106972874-7f7e3200-6730-11eb-8811-262725a0d2b3.png)

My ISP speed is 120 Mbps and the graph makes more sense in Mbps;

@fmdlc can you check later if I am right?

**Comment by fmdlc** [comment]
Hi @lcsvcn, depending the version, values are in Megabytes per second, and not MBPS
